export const attributes = {
  mu: "mu",
  in: "in",
  kl: "kl",
  ch: "ch",
  ko: "ko",
  kk: "kk",
  ge: "ge",
  ff: "ff"
}

export const skills = [
  { name: "Körpertalente",
    list: [
      { name: "Fliegen", attributes: [attributes.mu, attributes.in, attributes.ge]},
      { name: "Gaukeleien", attributes: [attributes.mu, attributes.ch, attributes.ff]},
      { name: "Klettern", attributes: [attributes.mu, attributes.ge, attributes.kk]},
      { name: "Koerperbeherrschung", attributes: [attributes.mu, attributes.ge, attributes.kk]},
      { name: "Kraftakt", attributes: [attributes.ko, attributes.kk, attributes.kk]},
      { name: "Reiten", attributes: [attributes.ch, attributes.ge, attributes.kk]},
      { name: "Schwimmen", attributes: [attributes.ge, attributes.ko, attributes.kk]},
      { name: "Selbstbeherrschung", attributes: [attributes.mu, attributes.mu, attributes.ko]},
      { name: "Singen", attributes: [attributes.kl, attributes.ch, attributes.ko]},
      { name: "Sinnesschaerfe", attributes: [attributes.kl, attributes.in, attributes.in]},
      { name: "Tanzen", attributes: [attributes.kl, attributes.ch, attributes.ge]},
      { name: "Taschendiebstahl", attributes: [attributes.mu, attributes.ff, attributes.ge]},
      { name: "Verbergen", attributes: [attributes.mu, attributes.in, attributes.ge]},
      { name: "Zechen", attributes: [attributes.kl, attributes.ko, attributes.kk]},
    ]
  },
  { name: "Gesellschaftstalente",
    list: [
      { name: "Bekehren & Überzeugen", attributes: [attributes.mu, attributes.kl, attributes.ch]},
      { name: "Betoeren", attributes: [attributes.mu, attributes.ch, attributes.ch]},
      { name: "Einschuechtern", attributes: [attributes.mu, attributes.in, attributes.ch]},
      { name: "Etikette", attributes: [attributes.kl, attributes.in, attributes.ch]},
      { name: "Gassenwissen", attributes: [attributes.kl, attributes.in, attributes.ch]},
      { name: "Menschenkenntnis", attributes: [attributes.kl, attributes.in, attributes.ch]},
      { name: "Ueberreden", attributes: [attributes.mu, attributes.in, attributes.ch]},
      { name: "Verkleiden", attributes: [attributes.in, attributes.ch, attributes.ge]},
      { name: "Willenskraft", attributes: [attributes.mu, attributes.in, attributes.ch]},
    ]
  },
  { name: "Naturtalente",
    list: [
      { name: "Faehrtensuchen", attributes: [attributes.mu, attributes.in, attributes.ge]},
      { name: "Fesseln", attributes: [attributes.kl, attributes.ff, attributes.kk]},
      { name: "Fischen & Angeln", attributes: [attributes.ff, attributes.ge, attributes.ko]},
      { name: "Pflanzenkunde", attributes: [attributes.kl, attributes.ff, attributes.ko]},
      { name: "Tierkunde", attributes: [attributes.mu, attributes.mu, attributes.ch]},
      { name: "Wildnisleben", attributes: [attributes.mu, attributes.ge, attributes.ko]},
    ]
  },
  { name: "Wissenstalente",
    list: [
      { name: "Brett- & Gluecksspiel", attributes: [attributes.kl, attributes.kl, attributes.in]},
      { name: "Geographie", attributes: [attributes.kl, attributes.kl, attributes.in]},
      { name: "Geschichtswissen", attributes: [attributes.kl, attributes.kl, attributes.in]},
      { name: "Goetter & Kulte", attributes: [attributes.kl, attributes.kl, attributes.in]},
      { name: "Kriegskunst", attributes: [attributes.mu, attributes.kl, attributes.in]},
      { name: "Magiekunde", attributes: [attributes.kl, attributes.kl, attributes.in]},
      { name: "Mechanik", attributes: [attributes.kl, attributes.kl, attributes.ff]},
      { name: "Rechnen", attributes: [attributes.kl, attributes.kl, attributes.in]},
      { name: "Rechtskunde", attributes: [attributes.kl, attributes.kl, attributes.in]},
      { name: "Sagen & Legenden", attributes: [attributes.kl, attributes.kl, attributes.in]},
      { name: "Sphaerenkunde", attributes: [attributes.kl, attributes.kl, attributes.in]},
      { name: "Sternkunde", attributes: [attributes.kl, attributes.kl, attributes.in]},
    ]
  },
  { name: "Handwerkstalente",
    list: [
      { name: "Alchimie", attributes: [attributes.mu, attributes.kl, attributes.ff]},
      { name: "Boote & Schiffe", attributes: [attributes.ff, attributes.ge, attributes.kk]},
      { name: "Fahrzeuge", attributes: [attributes.ch, attributes.fe, attributes.ko]},
      { name: "Handeln", attributes: [attributes.kl, attributes.in, attributes.ch]},
      { name: "Heilkunde Gift", attributes: [attributes.mu, attributes.kl, attributes.in]},
      { name: "Heilkunde Krankheiten", attributes: [attributes.mu, attributes.in, attributes.ko]},
      { name: "Heilkunde Seele", attributes: [attributes.in, attributes.ch, attributes.ko]},
      { name: "Heilkunde Wunden", attributes: [attributes.kl, attributes.ff, attributes.ff]},
      { name: "Holzbearbeitung", attributes: [attributes.ff, attributes.ge, attributes.kk]},
      { name: "Lebensmittelbearbeitung", attributes: [attributes.in, attributes.ff, attributes.ff]},
      { name: "Lederbearbeitung", attributes: [attributes.ff, attributes.ge, attributes.ko]},
      { name: "Malen & Zeichnen", attributes: [attributes.in, attributes.ff, attributes.ff]},
      { name: "Metallbearbeitung", attributes: [attributes.ff, attributes.ko, attributes.kk]},
      { name: "Musizieren", attributes: [attributes.ch, attributes.ff, attributes.ko]},
      { name: "Schloesserknacken", attributes: [attributes.in, attributes.ff, attributes.ff]},
      { name: "Steinbearbeitung", attributes: [attributes.ff, attributes.ff, attributes.kk]},
      { name: "Stoffbearbeitung", attributes: [attributes.kl, attributes.ff, attributes.ff]},
    ]
  },
]